### ISSUE TITLE
El tamaño del archivo cvs_001_3785.csv no puede ser mayor a bytes 

### ISSUE THREAD

**Issue by gvanesa** [gvanesa/ddjjF800#1]
1,03 KB, peso real del archivo
Se encuentra formado por 5 lineas 

Contenido del archivo:
133003,600008,5,34,129.88
1,1,012085,20160901,11:00,21164029,BASE,300443,012085160901567,0001,38.17,3.82,50.00,6,22.92
2,1,012085,20160901,12:00,21164029,BASE,300443,012085160901567,0001,38.17,3.82,50.00,1,3.82
3,1,012085,20160901,13:00,21164029,BASE,300443,012085160901567,0001,38.17,3.82,50.00,9,34.38
4,1,012085,20160901,14:00,21164029,BASE,300443,012085160901567,0001,38.17,3.82,50.00,9,34.38
5,1,012085,20160901,15:00,21164029,BASE,300443,012085160901567,0001,38.17,3.82,50.00,9,34.38

**Comment by jtuozzo** [comment]
No estaba configurado el parámetro que maneja el tamaño máximo de upload.
Corregido, hay que desloguearse y loguearse nuevamente.

**Comment by gvanesa** [comment]
ok
