### ISSUE TITLE
Subir un csv a ddjj.incaa.gov.ar/test_3785/

### ISSUE THREAD

**Issue by gvanesa** [gvanesa/ddjjF800#10]
Procesando archivo 600402-2016_09_30_10_57_55-dgomez.csv

Procesando

INCAA 

Error de conexión 1049. 

01/11/2016 15:45:24 

Favor informar al correo electrónico fiscaliza@incaa.gov.ar 

Disculpe las molestias ocasionadas, los solucionaremos a la brevedad.
Muchas gracias.

**Comment by jtuozzo** [comment]
Listo, logout / login para que levante los parámetros.

**Comment by gvanesa** [comment]
ok
