### ISSUE TITLE
RECTIFICAR MANUAL F700

### ISSUE THREAD

**Issue by gvanesa** [gvanesa/ddjjF800#11]
ingresar con mromeo pass 12345678 
Carga Manual f700
Editar la linea 1
el impuesto se calcula mal.

**Comment by jtuozzo** [comment]
NdJ: Quitar librería accounting.min.js

**Comment by jtuozzo** [comment]
Listo! Se sube el día 04/11

**Comment by gvanesa** [comment]
ok
