### ISSUE TITLE
Administración | usuario nuevo

### ISSUE THREAD

**Issue by gvanesa** [gvanesa/ddjjF800#2]
Al crear un usuario nuevo.
1_Cargar datos.
2_"Guardar"
Muestra la imagen de inicio y ningun 
![bug](https://cloud.githubusercontent.com/assets/242282/19689247/18bd9f8c-9aa3-11e6-8b91-06955364da2c.jpg)
cartel de confirmación.

**Comment by jtuozzo** [comment]
Me podrás mandar el contenido de:
http://192.168.16.33/desa/DDJJ/4_00/aplic/db_error_log.txt

**Comment by gvanesa** [comment]
ok
