### ISSUE TITLE
CARGA DE ARCHIVO CSV 001

### ISSUE THREAD

**Issue by gvanesa** [gvanesa/ddjjF800#5]
Procesando archivo Formulario 700

Procesando

INCAA 

Error de conexión 201. 

27/10/2016 16:19:42 

Favor informar al correo electrónico fiscaliza@incaa.gov.ar 

Disculpe las molestias ocasionadas, los solucionaremos a la brevedad.
Muchas gracias.

**Comment by gvanesa** [comment]
Tenemos red!!
tu pc responde ping

**Comment by gvanesa** [comment]
sigue tirandome este error

**Comment by jtuozzo** [comment]
Corregido.

**Comment by gvanesa** [comment]
OK
