### ISSUE TITLE
DECLARAR F700 CSV | error de la suma renglones cuando esta es correcta.

### ISSUE THREAD

**Issue by gvanesa** [gvanesa/ddjjF800#9]
Estos son los errores que muestra en el mensaje, y excepto el 0(renglon) todos los demas estan bien.

Fila Campo Contenido Mensaje de error
0 Registro Cabecera El monto total del impuesto declarado en la cabecera (72.58) no coincide con
la suma de los renglones (22.919999999999998)
1 Código de distribuidor 300444 El código de distribuidor no corresponde a la película
2 Código de distribuidor El código de distribuidor no corresponde a la película
2 Serie del BOC 023254160912567 La fecha de la serie del BOC no coincide con la fecha de la función que se
informa
3 Serie del BOC 0232541091056800 La serie del BOC debe tener 1 ó 15 dígitos
4 Serie del BOC La serie del BOC debe tener 1 ó 15 dígitos
5 Serie del BOC NC La serie del BOC debe tener 1 ó 15 dígitos

**Comment by jtuozzo** [comment]
¿Podrás mandarme el CSV?

**Comment by gvanesa** [comment]
[cvs_008.0.txt](https://github.com/gvanesa/ddjjF800/files/564685/cvs_008.0.txt)

**Comment by jtuozzo** [comment]
Listo! Se sube la corrección el 04/11

**Comment by gvanesa** [comment]
Ok
